apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp-deployment
  labels:
    app: demowebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demowebapp
  template:
    metadata:
      labels:
        app: demowebapp
    spec:
      containers:
      - name: demowebapp
        image: replace
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demowebapp-svc
  labels:
    eapp: demowebapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demowebapp